# Generated by Django 4.2 on 2023-10-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_user_is_premium_video_is_premium_alter_comment_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
