# Generated by Django 4.2 on 2023-10-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_video_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_liked_videos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='show_watched_videos',
            field=models.BooleanField(default=False),
        ),
    ]
