# Generated by Django 4.2 on 2023-10-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='like_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='message_notification',
            field=models.BooleanField(default=False),
        ),
    ]
