# Generated by Django 4.2 on 2023-11-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_premiumplan_user_premium_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
